server:
  port: 8081
#  DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vueadmin?useSSL=false&serverTimezone=UTC
    username: "root"
    password: "000000"
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 0
  main:
    banner-mode: off
#  security:
#    user:
#      name: "user"
#      password: "000000"
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

markerhub:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

#logging:
#  level:
#    root: warn
#    org:
#      springframework: warn
#debug: true


